"""Train Random Forest, evaluate, and export a C header for the ESP32."""
import time, os
import numpy as np, joblib
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from data_gen import make_dataset, gen, CLASSES, FS, N
from features import features, spectrum, FEATURE_NAMES


def _fmt(v):
    t = f"{float(v):.9g}"
    if not any(ch in t for ch in ".en"):
        t += ".0"
    return t + "f"


def export_rf_to_c(clf, path):
    nt = len(clf.estimators_)
    nc = len(clf.classes_)
    out = ["// Auto-generated by train.py. Random Forest -> C (no dependencies).",
           "#pragma once", f"#define RF_N_CLASSES {nc}", f"#define RF_N_FEATURES {clf.n_features_in_}", ""]
    for ti, est in enumerate(clf.estimators_):
        tr = est.tree_

        def rec(node, ind):
            pad = "  " * ind
            if tr.children_left[node] == -1:
                v = tr.value[node][0]
                v = v / v.sum()
                return pad + " ".join(f"p[{c}]+={_fmt(v[c])};" for c in range(nc) if v[c] > 0) + "\n"
            s = f"{pad}if (x[{tr.feature[node]}] <= {_fmt(tr.threshold[node])}) {{\n"
            s += rec(tr.children_left[node], ind + 1)
            s += f"{pad}}} else {{\n"
            s += rec(tr.children_right[node], ind + 1)
            return s + f"{pad}}}\n"
        out.append(f"static void rf_tree_{ti}(const float *x, float *p) {{\n{rec(0, 1)}}}\n")
    out.append("// returns predicted class; proba[RF_N_CLASSES] receives probabilities")
    out.append("static int rf_predict(const float *x, float *proba) {")
    out.append(f"  for (int c = 0; c < {nc}; c++) proba[c] = 0;")
    out += [f"  rf_tree_{i}(x, proba);" for i in range(nt)]
    out.append(f"  int best = 0;\n  for (int c = 0; c < {nc}; c++) {{ proba[c] /= {nt}.0f; if (proba[c] > proba[best]) best = c; }}")
    out.append("  return best;\n}")
    import os
    if os.path.dirname(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    os.makedirs("results", exist_ok=True)
    X, y = make_dataset(400, seed=0)
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.20, stratify=y, random_state=42)
    clf = RandomForestClassifier(n_estimators=16, max_depth=8, random_state=42).fit(Xtr, ytr)
    pred = clf.predict(Xte)
    print(classification_report(yte, pred, target_names=CLASSES, digits=3))
    cv = cross_val_score(RandomForestClassifier(n_estimators=16, max_depth=8, random_state=42), X, y, cv=5)
    print(f"5-fold CV accuracy: {cv.mean():.3f} +/- {cv.std():.3f}")

    ConfusionMatrixDisplay(confusion_matrix(yte, pred), display_labels=CLASSES).plot(xticks_rotation=30, cmap="Blues")
    plt.tight_layout(); plt.savefig("results/confusion_matrix.png", dpi=150); plt.close()

    imp = clf.feature_importances_
    plt.figure(figsize=(7, 3.5)); plt.bar(FEATURE_NAMES, imp); plt.xticks(rotation=45, ha="right")
    plt.title("Feature importance"); plt.tight_layout(); plt.savefig("results/feature_importance.png", dpi=150); plt.close()

    # waveform + spectrum per class (use in PPT slide 7)
    rng = np.random.default_rng(5)
    fig, ax = plt.subplots(5, 2, figsize=(10, 10))
    for c in range(5):
        x = gen(c, rng); fr, F = spectrum(x)
        ax[c, 0].plot(np.arange(400) / FS * 1000, x[:400]); ax[c, 0].set_ylabel(CLASSES[c])
        ax[c, 1].plot(fr, F); ax[c, 1].set_xlim(0, 1000)
    ax[0, 0].set_title("Waveform (ms)"); ax[0, 1].set_title("Spectrum (Hz)")
    plt.tight_layout(); plt.savefig("results/signatures.png", dpi=130); plt.close()

    # timing on this PC (ESP32 is slower; measure real value in firmware)
    xs = [gen(i % 5, rng) for i in range(200)]
    t0 = time.perf_counter()
    for x in xs:
        clf.predict([features(x)])
    print(f"PC feature+inference time: {(time.perf_counter() - t0) / 200 * 1000:.2f} ms/window")

    joblib.dump(clf, "results/model.joblib")
    export_rf_to_c(clf, "model.h")
    export_rf_to_c(clf, "esp32_wokwi/model.h")
    print(f"model.h size: {os.path.getsize('model.h') / 1024:.1f} KB (source); "
          f"total tree nodes: {sum(e.tree_.node_count for e in clf.estimators_)}")
