// Auto-generated by train.py. Random Forest -> C (no dependencies).
#pragma once
#define RF_N_CLASSES 5
#define RF_N_FEATURES 12

static void rf_tree_0(const float *x, float *p) {
  if (x[8] <= 0.249246683f) {
    if (x[4] <= 0.215412751f) {
      if (x[1] <= 1.39181709f) {
        p[0]+=1.0f;
      } else {
        p[1]+=1.0f;
      }
    } else {
      p[3]+=1.0f;
    }
  } else {
    if (x[6] <= 37.109375f) {
      p[4]+=1.0f;
    } else {
      p[2]+=1.0f;
    }
  }
}

static void rf_tree_1(const float *x, float *p) {
  if (x[5] <= 0.610175371f) {
    if (x[10] <= 0.556915879f) {
      p[0]+=1.0f;
    } else {
      p[3]+=1.0f;
    }
  } else {
    if (x[7] <= 0.47865507f) {
      p[2]+=1.0f;
    } else {
      if (x[10] <= 0.55892545f) {
        p[1]+=1.0f;
      } else {
        p[4]+=1.0f;
      }
    }
  }
}

static void rf_tree_2(const float *x, float *p) {
  if (x[7] <= 0.47993663f) {
    if (x[5] <= 0.621473879f) {
      if (x[10] <= 0.573107004f) {
        p[0]+=1.0f;
      } else {
        p[3]+=1.0f;
      }
    } else {
      p[2]+=1.0f;
    }
  } else {
    if (x[3] <= -1.21585757f) {
      p[1]+=1.0f;
    } else {
      p[4]+=1.0f;
    }
  }
}

static void rf_tree_3(const float *x, float *p) {
  if (x[0] <= 0.609544337f) {
    if (x[4] <= 0.198440861f) {
      p[0]+=1.0f;
    } else {
      p[3]+=1.0f;
    }
  } else {
    if (x[3] <= -1.38605762f) {
      p[1]+=1.0f;
    } else {
      if (x[9] <= 0.104816563f) {
        if (x[8] <= 0.548146307f) {
          p[4]+=1.0f;
        } else {
          p[2]+=1.0f;
        }
      } else {
        if (x[10] <= 0.548141003f) {
          p[2]+=1.0f;
        } else {
          p[4]+=1.0f;
        }
      }
    }
  }
}

static void rf_tree_4(const float *x, float *p) {
  if (x[1] <= 1.29019636f) {
    p[0]+=1.0f;
  } else {
    if (x[5] <= 0.609769762f) {
      p[3]+=1.0f;
    } else {
      if (x[6] <= 37.109375f) {
        if (x[3] <= -1.21732515f) {
          p[1]+=1.0f;
        } else {
          p[4]+=1.0f;
        }
      } else {
        p[2]+=1.0f;
      }
    }
  }
}

static void rf_tree_5(const float *x, float *p) {
  if (x[7] <= 0.480496556f) {
    if (x[1] <= 1.25969964f) {
      p[0]+=1.0f;
    } else {
      if (x[8] <= 0.33063174f) {
        p[3]+=1.0f;
      } else {
        p[2]+=1.0f;
      }
    }
  } else {
    if (x[9] <= 0.109468237f) {
      if (x[3] <= -1.08155727f) {
        p[1]+=1.0f;
      } else {
        p[4]+=1.0f;
      }
    } else {
      if (x[9] <= 0.125203621f) {
        if (x[11] <= 0.776859343f) {
          p[1]+=1.0f;
        } else {
          p[4]+=1.0f;
        }
      } else {
        p[4]+=1.0f;
      }
    }
  }
}

static void rf_tree_6(const float *x, float *p) {
  if (x[7] <= 0.477900669f) {
    if (x[0] <= 0.622785121f) {
      if (x[0] <= 0.411398768f) {
        if (x[3] <= -0.283896267f) {
          p[0]+=1.0f;
        } else {
          p[3]+=1.0f;
        }
      } else {
        if (x[1] <= 1.24179232f) {
          p[0]+=1.0f;
        } else {
          p[3]+=1.0f;
        }
      }
    } else {
      p[2]+=1.0f;
    }
  } else {
    if (x[0] <= 0.948155046f) {
      p[4]+=1.0f;
    } else {
      p[1]+=1.0f;
    }
  }
}

static void rf_tree_7(const float *x, float *p) {
  if (x[0] <= 0.607870877f) {
    if (x[3] <= -0.381344467f) {
      p[0]+=1.0f;
    } else {
      p[3]+=1.0f;
    }
  } else {
    if (x[10] <= 0.55892545f) {
      if (x[2] <= 1.8765887f) {
        if (x[3] <= -1.40755701f) {
          p[1]+=1.0f;
        } else {
          p[2]+=1.0f;
        }
      } else {
        if (x[0] <= 0.982858807f) {
          p[2]+=1.0f;
        } else {
          p[1]+=1.0f;
        }
      }
    } else {
      p[4]+=1.0f;
    }
  }
}

static void rf_tree_8(const float *x, float *p) {
  if (x[6] <= 37.109375f) {
    if (x[7] <= 0.467100531f) {
      if (x[10] <= 0.558015764f) {
        p[0]+=1.0f;
      } else {
        p[3]+=1.0f;
      }
    } else {
      if (x[8] <= 0.243700299f) {
        p[1]+=1.0f;
      } else {
        p[4]+=1.0f;
      }
    }
  } else {
    p[2]+=1.0f;
  }
}

static void rf_tree_9(const float *x, float *p) {
  if (x[3] <= -1.4060744f) {
    p[1]+=1.0f;
  } else {
    if (x[7] <= 0.47865507f) {
      if (x[3] <= 0.137798734f) {
        if (x[8] <= 0.333126735f) {
          p[0]+=1.0f;
        } else {
          p[2]+=1.0f;
        }
      } else {
        p[3]+=1.0f;
      }
    } else {
      p[4]+=1.0f;
    }
  }
}

// returns predicted class; proba[RF_N_CLASSES] receives probabilities
static int rf_predict(const float *x, float *proba) {
  for (int c = 0; c < 5; c++) proba[c] = 0;
  rf_tree_0(x, proba);
  rf_tree_1(x, proba);
  rf_tree_2(x, proba);
  rf_tree_3(x, proba);
  rf_tree_4(x, proba);
  rf_tree_5(x, proba);
  rf_tree_6(x, proba);
  rf_tree_7(x, proba);
  rf_tree_8(x, proba);
  rf_tree_9(x, proba);
  int best = 0;
  for (int c = 0; c < 5; c++) { proba[c] /= 10.0f; if (proba[c] > proba[best]) best = c; }
  return best;
}